### ISSUE TITLE
Overflow Condition needs to be addressed

### ISSUE THREAD

**Issue by Zafeeruddin** [FK04/AI_Lab#2]
--> Pouring Water Completely from A to B or vice versa requires attention, as it exceeds the capacity initially specified.
```
        elif(op==7):
		ai=ai+bi
		bi=0
	elif(op==8):
		bi=bi+ai
		ai=0`
```

**Comment by mssanamateen** [comment]
Thank you for suggesting the change Main contributor shall resolve the issue soon.
